# Generated by Django 4.0.5 on 2022-06-17 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
