# Generated by Django 4.0.5 on 2022-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_title_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
