# Generated by Django 4.0.5 on 2022-06-17 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 27, 52, 982137)),
        ),
    ]
