# Generated by Django 4.0.5 on 2022-06-17 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 33, 45, 323158)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 33, 45, 323142)),
        ),
    ]
