# Generated by Django 4.0.5 on 2022-06-17 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_post_published_date_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 36, 46, 415453)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 36, 46, 415469)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
