# Generated by Django 4.0.5 on 2022-06-17 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_author_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 37, 38, 647966)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 37, 38, 647983)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
